### PR TITLE
replace "Open shared tab" link with collapsible area

### PR DESCRIPTION
**Pull request by xMartin**
the link behavior was a bit weird: you can only open and never close again. and the label sounds more like you're actually importing. the new appearance as a collapsible field is supposed to improve on that.

additionally, set back to collapsed state after importing

bildschirmfoto 2016-11-13 um 16 41 12
bildschirmfoto 2016-11-13 um 16 41 21

### CODE REVIEW

**Comment by jancborchardt** [comment]
I'd just make 2 adjustments:
- put the triangle right of the text
- make it point downwards even when closed, cause it signifies where it opens to

**Comment by jancborchardt** [comment]
Oh and the greying of the current link is better. Takes less focus away of the primary action, being the creation of a new tab.

**Comment by xMartin** [comment]
I doubt that a gray text with a triangle pointing down next to it will be understood. Currently the underline makes it at least look interactive. I think the triangle on the left pointing to the right is a learned pattern from collapsible areas. But I'm also not a fan.

**Comment by jancborchardt** [comment]
On Facebook etc there are downward pointing triangles on the top right menus. ;)

We can either make it underlined or a button. Also yes, the shade of grey is a bit light, we can darken it.

**Comment by xMartin** [comment]
@jancborchardt Ok, in a context of a menu bar, that works.

**Comment by jancborchardt** [comment]
This would be replaced by https://github.com/xMartin/grouptabs/issues/104#issuecomment-373162110

**Pull request closed without merging**
