### PR TITLE
Move "save" button to top right

### PR DESCRIPTION
**Pull request by xMartin**
See #90 

bildschirmfoto 2016-11-06 um 23 37 35

### CODE REVIEW

**Comment by jancborchardt** [comment]
Then now let's make the delete button small, not full width for sure ;)

Even better, just a text link like the "Open shared tab" link. It should not be attention-grabbing.

**Comment by xMartin** [comment]
@jancborchardt  Ok, makes sense.

**Comment by xMartin** [comment]
@jancborchardt Currently, as we don't have a sticky header, moving the "save" button up doesn't make too much sense to me, though.

**Comment by jancborchardt** [comment]
Good point. Do we want to make the whole header sticky, or only the save button?

**Comment by jancborchardt** [comment]
Ready for review :rocket:

**Comment by jancborchardt** [comment]
What do you think now @xMartin? Let’s go for it?

**Comment by xMartin** [comment]
I'd do the change to the "delete" button, too (make it a text link to not make it so prominent) before merging.

**Comment by xMartin** [comment]
This is how it looks now: 
bildschirmfoto 2017-03-10 um 23 35 42

**Comment by xMartin** [comment]
I also added a confirm dialog ("Do you really want to delete the transaction").

@jancborchardt I know you're not a fan and you want undo but we don't have it, yet, and I think destructive actions should have a confirmation.

**Comment by jancborchardt** [comment]
Ok cool! I’d keep the red coloring we had for the button, and use it as text color. That makes immediately visible that the action is destructive.

**Comment by xMartin** [comment]
bildschirmfoto 2017-03-12 um 23 06 09

**Pull request merged**
