### PR TITLE
Add dark mode

### LINKED ISSUE #177: Add dark mode
https://css-tricks.com/dark-modes-with-css/

### PR DESCRIPTION
**Pull request by xMartin**
closes #177

Bildschirmfoto 2020-06-02 um 15 50 45
Bildschirmfoto 2020-06-02 um 15 50 51
Bildschirmfoto 2020-06-02 um 15 51 07

### CODE REVIEW

**Comment by xMartin** [comment]
* Dark line is probably only a debug mode rendering glitch.
* I wanted to make the colors less bright for dark mode only but wasn't easy so I skipped it. Changing then for light and dark would be better of course but currently those very colors are part of our corporate style I'd say (see logo). Happy if you propose something here. Changing text color contextually could work but might look wierd and unexpected.
* Yes, I noticed but was sloppy. Didn't try, yet.

Please let me know what you think are blocking issues for this to merge.

**Comment by xMartin** [comment]
@jancborchardt Dark font color on bright account colors:
Bildschirmfoto 2020-06-04 um 00 12 52

**Comment by xMartin** [comment]
Calendar icon seems to be very browser specific and hard or impossible to change in Chrome. Would like to leave it as it is for now.

**Comment by jancborchardt** [comment]
Sure, sounds good like this :)

**Pull request merged**
