### PR TITLE
add GPLv3 license, fix #107

### LINKED ISSUE #107: License
While running npm install I just discovered that the license info is missing.
And it’s nowhere to be found …

@xMartin we are working on practically closed-source software! How can you do this to me? :scream: 

Let’s use AGPL. (Or if you don’t like that, MIT.) What do you think?

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #107, please review @xMartin @hugoroy @schiessle :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
As copyright header I suggest a very very short one, like:
> Copyright (C) 2017 Martin Stadler
> Licensed under GPLv3+, see README.md

**Comment by xMartin** [comment]
I checked how Drupal is doing it and this seems reasonable: No header in files but a COPYRIGHT file: https://github.com/drupal/drupal/blob/8.4.x/core/COPYRIGHT.txt

**Comment by hugoroy** [comment]
See http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html for best practices ;-)

**Comment by jancborchardt** [comment]
@xMartin I added the COPYRIGHT.txt and also put the license in the package.json. :) Over time we can add the library copyrights in the copyright.txt – but let’s merge this now and do that in a follow-up?

**Pull request merged**
