### PR TITLE
Direct transaction design

### PR DESCRIPTION
**Pull request by jancborchardt**
TODO:

- [x] Make switcher work again with new layout
- [ ] ~~Left dropdown should show person who needs to pay most, right one person who needs to pay least~~ → https://github.com/xMartin/grouptabs/issues/157
- [x] Ensure that Shared/Direct switcher is on Direct when editing existing direct transactions

### CODE REVIEW

**Comment by jancborchardt** [comment]
Current state:
screenshot from 2017-11-29 19-03-08
Another quick mockup of a proposal:
grouptabs direct transaction

**Comment by jancborchardt** [comment]
@xMartin what do we need to absolutely fix in this PR to make it as a first testable version?

**Comment by xMartin** [comment]
Functionality is implemented except "Left dropdown should show person who needs to pay most, right one person who needs to pay least" which is quite complicated.

I don't think it's a good UX currently. @jancborchardt please review.

**Comment by jancborchardt** [comment]
Inline SVG for "arrow down":
```
<svg width="16" height="16" version="1.1" viewbox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="m15.511 8.5129c0-0.8974-1.0909-1.3404-1.7168-0.6973l-4.7832 4.7837v-11.573c0.019125-1.3523-2.0191-1.3523-2 0v11.572l-4.7832-4.7832c-0.94251-0.98163-2.3957 0.47155-1.4141 1.4141l6.49 6.4911c0.3878 0.387 1.0228 0.391 1.414 0l6.4903-6.4906c0.1935-0.1883 0.30268-0.4468 0.3027-0.7168z"/></svg>
```

**Comment by jancborchardt** [comment]
Works very very nicely! :) 

Do you want to do this also in this pull request:

> Left dropdown should show person who needs to pay most, right one person who needs to pay least

or should we merge and I open a separate issue for that?

**Comment by xMartin** [comment]
That can be a separate issue.

But I think we should have support for new participants before we merge this.

**Comment by jancborchardt** [comment]
Opened the issue at https://github.com/xMartin/grouptabs/issues/157

> But I think we should have support for new participants before we merge this.

Yes, good point. Do your magic. ;)

**Comment by xMartin** [comment]
:sparkles:

**Comment by jancborchardt** [comment]
Fine to merge from my side, tested and works well! :)

**Pull request merged**
